select GX_NE_GRID.POLYGONID as "POLYGON ID",
    GX_NE_GRID.NE_TOWNSHIP_NAME as "TOWNSHIP NAME",
    GX_NE_GRID.NE_DISTRICT as DISTRICT,GX_NE_GRID.REF_LONGITUDE as LONGITUDE,
    GX_NE_GRID.REF_LATITUDE as LATITUDE,
    GX_NE_GRID.PROVINCE_STATE as "STATE/PROVINCE",GX_NE_GRID.COUNTY as COUNTY,
    GX_NE_GRID.MINX as "MINIMUM X",GX_NE_GRID.MINY as "MINIMUM Y",
    GX_NE_GRID.MAXX as "MAXIMUM X",GX_NE_GRID.MAXY as "MAXIMUM Y",
    GX_NE_GRID.MAJORCODE as "MAJOR CODE",GX_NE_GRID.MINORCODE as "MINOR CODE",
    GX_NE_GRID.ISPARTIAL as "IS PARTIAL",GX_NE_GRID.POLYGONBLOB as "POLYGON BLOB"
    from DBA.GX_NE_GRID 
    ORDER BY "POLYGON ID";