select GX_CARTER_GRID.POLYGONID as "POLYGON ID",GX_CARTER_GRID.RANGE as RANGE,
    GX_CARTER_GRID.RANGEDIRECTION as "RANGE DIRECTION",
    GX_CARTER_GRID.SECTION as SECTION,GX_CARTER_GRID.TOWNSHIP as TOWNSHIP,
    GX_CARTER_GRID.MINX as "MINIMUM X",GX_CARTER_GRID.MINY as "MINIMUM Y",
    GX_CARTER_GRID.MAXX as "MAXIMUM X",GX_CARTER_GRID.MAXY as "MAXIMUM Y",
    GX_CARTER_GRID.MAJORCODE as "MAJOR CODE",
    GX_CARTER_GRID.MINORCODE as "MINOR CODE",
    GX_CARTER_GRID.ISPARTIAL as "IS PARTIAL",
    GX_CARTER_GRID.POLYGONBLOB as "POLYGON BLOB"
    from DBA.GX_CARTER_GRID
    ORDER BY POLYGONID;