select GX_PDEN_VOL_SUM_BY_MONTH.UWI as "Well ID",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_TYPE as "PDEN Type",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_SOURCE as Source,
    GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_METHOD as "Summary Type",
    GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID as Zone,
    DBA.GET_ZONE_ALIAS(GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID) as "Zone Alias",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_DATE as "Date",
    GX_PDEN_VOL_SUM_BY_MONTH.ACTIVITY_TYPE as "Activity Type",
    GX_PDEN_VOL_SUM_BY_MONTH.PRIMARY_PRODUCT as Product,
    GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Oil Volume",
    GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Gas Volume",
    GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Water Volume",
    GX_PDEN_VOL_SUM_BY_MONTH.CO2_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative CO2",
    GX_PDEN_VOL_SUM_BY_MONTH.INJECTION_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Injection",
    GX_PDEN_VOL_SUM_BY_MONTH.NGL_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative NGL",
    GX_PDEN_VOL_SUM_BY_MONTH.NITROGEN_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Nitrogen",
    GX_PDEN_VOL_SUM_BY_MONTH.SULPHUR_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Cumulative Sulphur",
    MAX((GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME+GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME)*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100) as "Cumulative Total Fluids",
    avg(case when WELL_FORMATION.UWI = GX_PDEN_VOL_SUM_BY_MONTH.UWI and WELL_FORMATION.FORM_ID = GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID then WELL_FORMATION.GX_FORM_TOP_DEPTH else null
    end) as "Top Depth" from dba.GX_PDEN_VOL_SUM_BY_MONTH
    join dba.WELL_FORMATION
    on GX_PDEN_VOL_SUM_BY_MONTH.UWI = WELL_FORMATION.UWI
    group by "Well ID","PDEN Type",Source,"Summary Type",Zone,"Date","Activity Type",
    Product,"Cumulative Oil Volume","Cumulative Gas Volume","Cumulative Water Volume","Cumulative CO2","Cumulative Injection","Cumulative NGL","Cumulative Nitrogen","Cumulative Sulphur"
    ORDER BY "Well ID"
	, "PDEN TYPE"
	, "Source"
	, "Summary Type"
	, "Zone"
	, "Date"
	, "Activity Type"
	;