select UWI as "Well ID",GX_PDEN_VOL_SUM_BY_MONTH.PDEN_SOURCE as Source,GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID as "Zone ID",
    GX_PDEN_VOL_SUM_BY_MONTH.PRIMARY_PRODUCT as Fluid,GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_YEAR as Year,GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_MONTH as Month,
    GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME as Gas,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME as Oil,GX_PDEN_VOL_SUM_BY_MONTH.NGL_VOLUME as NGL
    from DBA.GX_PDEN_VOL_SUM_BY_MONTH
    where GX_PDEN_VOL_SUM_BY_MONTH.PDEN_TYPE = 'WELL'
  ORDER BY "Well ID"
	, PDEN_TYPE
	, "Source"
	--, "Summary Type"
	, "Zone ID"
	--, "Date"
	--, "Activity Type"
    ;