select WELL_CHECKSHOT_SURVEY.UWI as "Well ID",
    WELL_CHECKSHOT_SURVEY.SOURCE as Source,
    WELL_CHECKSHOT_SURVEY.SURVEY_ID as "Survey ID",
    WELL_CHECKSHOT_SURVEY.SURVEY_TYPE as "Survey Type",
    WELL_CHECKSHOT_SURVEY.GX_USER1 as "Velocity Name",
    GX_WELL_SYNTHETIC.NAME as "Synthetic Name",
    GX_WELL_SYNTHETIC.DESCRIPTION as "Synthetic Description",
    WELL_CHECKSHOT_SURVEY.DATUM_ELEV as "Datum Elevation",
    WELL_CHECKSHOT_SURVEY.ACTIVE as Active
    from dba.WELL_CHECKSHOT_SURVEY left outer join dba.GX_WELL_SYNTHETIC on WELL_CHECKSHOT_SURVEY.UWI = GX_WELL_SYNTHETIC.UWI
    and WELL_CHECKSHOT_SURVEY.SURVEY_ID = GX_WELL_SYNTHETIC.SURVEY_ID 
    ORDER BY "Well ID"
    , "Source"
    , "Survey ID"
    ;