select WELL_TEST_PRESSURE.UWI as "Well ID",
    WELL_TEST_PRESSURE.TEST_TYPE as "Test Type",
    WELL_TEST_PRESSURE.TEST_NUMBER as "DST ID",
    WELL_TEST_PRESSURE.PERIOD_TYPE as "Period Type",
    WELL_TEST_PRESSURE.SOURCE as Source,
    WELL_TEST_PRESSURE.GX_DURATION as Duration,
    WELL_TEST_PRESSURE.START_PRESS as "Start Pressure",
    WELL_TEST_PRESSURE.END_PRESS as "End Pressure",
    WELL_TEST_PRESSURE.QUALITY_CODE as "Quality Code",
    WELL_TEST_PRESSURE.REMARK as Remarks,
    WELL_TEST_PRESSURE.RUN_NUMBER as "Run Number",
    WELL_TEST_FORMATION.FORM_ID as Formation,
    WELL_TEST_FORMATION.AGE_CODE as Age,
    WELL_TEST.TOP_DEPTH as "Top Depth",
    WELL_TEST.BASE_DEPTH as "Base Depth"
    from dba.WELL_TEST_PRESSURE
    join dba.WELL_TEST on(WELL_TEST_PRESSURE.UWI = WELL_TEST.UWI and WELL_TEST_PRESSURE.TEST_NUMBER = WELL_TEST.TEST_NUMBER and WELL_TEST_PRESSURE.TEST_TYPE = WELL_TEST.TEST_TYPE)
    left outer join dba.WELL_TEST_FORMATION on(WELL_TEST_PRESSURE.UWI = WELL_TEST_FORMATION.UWI and WELL_TEST_PRESSURE.TEST_NUMBER = WELL_TEST_FORMATION.TEST_NUMBER)
    where WELL_TEST_PRESSURE.TEST_TYPE = 'DST'
    ORDER BY  "Well ID"
        , "Test Type"
        , "DST ID"
        , "Period Type"
        , Source
        , "Run Number"
        ;
