select LEGAL_OFFSHORE_LOC.UWI as "Well ID",LEGAL_OFFSHORE_LOC.LOCATION_TYPE as Type,
    LEGAL_OFFSHORE_LOC.SOURCE as Source,
    LEGAL_OFFSHORE_LOC.BLOCK_ADDITION as "Block Add",
    LEGAL_OFFSHORE_LOC.BLOCK_MODIFIER as "Block Mod",
    LEGAL_OFFSHORE_LOC.GRID_BLOCK_EW as "Grid E/W",
    LEGAL_OFFSHORE_LOC.GRID_BLOCK_RANGE as Range,
    LEGAL_OFFSHORE_LOC.GRID_BLOCK_TIER as Tier,
    LEGAL_OFFSHORE_LOC.GRID_BLOCK_NS as "Grid N/S",
    LEGAL_OFFSHORE_LOC.NS_START_LINE as "N/S Start Line",
    LEGAL_OFFSHORE_LOC.NS_FOOTAGE as "N/S Footage",
    LEGAL_OFFSHORE_LOC.EW_START_LINE as "E/W Start Line",
    LEGAL_OFFSHORE_LOC.EW_FOOTAGE as "E/W Footage",
    LEGAL_OFFSHORE_LOC.FOOTAGE_ORIGIN as Origin,
    LEGAL_OFFSHORE_LOC.OCS_NUMBER as "OCS Number",
    LEGAL_OFFSHORE_LOC.OFFSHORE_BLOCK as Block,
    LEGAL_OFFSHORE_LOC.UTM_QUADRANT as Quadrant,
    LEGAL_OFFSHORE_LOC.OFFSHORE_AREA_CODE as Area,
    LEGAL_OFFSHORE_LOC.GOVERNING_AGENCY as Agency,
    LEGAL_OFFSHORE_LOC.WATER_BOTTOM_ZONE as "Water Zone",
    LEGAL_OFFSHORE_LOC.PROVINCE_STATE as State,
    LEGAL_OFFSHORE_LOC.COUNTY as County,LEGAL_OFFSHORE_LOC.COUNTRY as Country,
    LEGAL_OFFSHORE_LOC.REMARK as "Location Description",
    LEGAL_OFFSHORE_LOC.POLYGONID
    from dba.LEGAL_OFFSHORE_LOC
    ORDER BY "Well ID"
    , "Type"
    ;