select LEGAL_CONGRESS_LOC.UWI as "Well ID",LEGAL_CONGRESS_LOC.LOCATION_TYPE as Type,
    LEGAL_CONGRESS_LOC.SOURCE as Source,
    LEGAL_CONGRESS_LOC.CONGRESS_RANGE as Range,
    LEGAL_CONGRESS_LOC.CONGRESS_SECT_SUFFIX as "Section Suffix",
    LEGAL_CONGRESS_LOC.EW_DIRECTION as "E/W Direction",
    LEGAL_CONGRESS_LOC.CONGRESS_SECTION as Section,
    LEGAL_CONGRESS_LOC.CONGRESS_SECT_TYPE as "Section Type",
    LEGAL_CONGRESS_LOC.CONGRESS_TOWNSHIP as Township,
    LEGAL_CONGRESS_LOC.NS_DIRECTION as "N/S Direction",
    LEGAL_CONGRESS_LOC.CONGRESS_TWP_NAME as "TWP Name",
    LEGAL_CONGRESS_LOC.PRINCIPAL_MERIDIAN as Meridian,
    LEGAL_CONGRESS_LOC.NS_FOOTAGE as "N/S Footage",
    LEGAL_CONGRESS_LOC.NS_START_LINE as "N/S Start Line",
    LEGAL_CONGRESS_LOC.EW_FOOTAGE as "E/W Footage",
    LEGAL_CONGRESS_LOC.EW_START_LINE as "E/W Start Line",
    LEGAL_CONGRESS_LOC.FOOTAGE_ORIGIN as Origin,
    LEGAL_CONGRESS_LOC.SPOT_CODE as "Spot Code",
    LEGAL_CONGRESS_LOC.PROVINCE_STATE as State,
    LEGAL_CONGRESS_LOC.COUNTY as County,LEGAL_CONGRESS_LOC.COUNTRY as Country,
    LEGAL_CONGRESS_LOC.REMARK as "Location Description",
    LEGAL_CONGRESS_LOC.POLYGONID,
    LEGAL_CONGRESS_LOC.BH_FLAG as "BH Flag"
    from dba.LEGAL_CONGRESS_LOC
    ORDER BY "Well ID"
    , "Type"
    ;