select LEGAL_CONGRESS_LOC.UWI as "Well ID",LEGAL_CONGRESS_LOC.LOCATION_TYPE as Type,
    LEGAL_CONGRESS_LOC.SOURCE as Source,
    LEGAL_CONGRESS_LOC.CONGRESS_RANGE as Range,
    LEGAL_CONGRESS_LOC.EW_DIRECTION as "E/W Dir",
    LEGAL_CONGRESS_LOC.CONGRESS_SECTION as Section,
    LEGAL_CONGRESS_LOC.CONGRESS_TOWNSHIP as Township,
    LEGAL_CONGRESS_LOC.NS_DIRECTION as "N/S Dir",
    LEGAL_CONGRESS_LOC.PRINCIPAL_MERIDIAN as Meridian
    from dba.LEGAL_CONGRESS_LOC
    ORDER BY "Well ID"
    , "Type"
    ;