SELECT 
WELL.UWI                        AS "Well ID",
WELL.PRIMARY_SOURCE             AS Source,
WELL.OPERATOR                   AS Operator,
WELL.PROVINCE_STATE             AS State,
WELL.COUNTY                     AS County,
WELL.COUNTRY                    AS Country,
WELL.WELL_NAME                  AS "Well Name",
WELL.WELL_NUMBER                AS "Well Number",
WELL.COMMON_WELL_NAME           AS "Common Well Name",
WELL.SURFACE_LATITUDE           AS Latitude,
WELL.SURFACE_LONGITUDE          AS Longitude,
WELL.CURRENT_STATUS             AS Status,
WELL.CURRENT_CLASS              AS Classification,
WELL.DEPTH_DATUM_ELEV           AS "Datum Elev",
WELL.GROUND_ELEV                AS "Ground Elev",
WELL.PLUGBACK_DEPTH             AS "Plugback Depth",
WELL.FINAL_TD                   AS TD,
WELL.TD_FORM                    AS "Fm at TD",
WELL.GX_TD_FORM_ALIAS           AS "Fm Alias at TD",
WELL.SPUD_DATE                  AS "Spud Date",
WELL.COMPLETION_DATE            AS "Comp Date",
WELL.GEOLOGIC_PROVINCE          AS Area,
WELL.DISTRICT                   AS District,
WELL.ASSIGNED_FIELD             AS Field,
WELL.WELL_GOVT_ID               AS "Permit Number",
WELL.DEPTH_DATUM                AS "Datum Type",
WELL.GX_ALTERNATE_ID            AS "Alternate ID",
WELL.GX_OLD_ID                  AS "Old ID",
WELL.GX_USER1                   AS "User 1",
WELL.GX_USER2                   AS "User 2",
WELL.LEASE_NAME                 AS "Lease Name",
WELL.PLATFORM_ID                AS "Platform ID",
WELL.WATER_DEPTH                AS "Water Depth",
WELL.WATER_DEPTH_DATUM          AS "Water Datum",
WELL.PARENT_RELATIONSHIP_TYPE   AS "Parent UWI Type",
WELL.GX_PERMIT_DATE             AS "Permit Date",
WELL.GX_USER_DATE               AS "User Date",
WELL.PARENT_UWI                 AS "Parent UWI",
WELL.LEGAL_SURVEY_TYPE          AS "Legal Survey Type",
WELL.GX_LOCATION_STRING         AS Location,
WELL.ORIGINAL_OPERATOR          AS "Original Operator",
WELL.GGX_INTERNAL_STATUS        AS "Internal Status",
WELL.GX_WSN                     AS "WSN",
WELL.GX_PROPOSED_FLAG           As "Proposed",
LEGAL_CONGRESS_LOC.REMARK       AS "Congress Location",
LEGAL_TEXAS_LOC.REMARK          AS "Texas Location",
LEGAL_OFFSHORE_LOC.REMARK       AS "Offshore Location",
LEGAL_DLS_LOC.REMARK            AS "DLS Location",
LEGAL_NE_LOC.REMARK             AS "NE Location"
FROM (((( dba.WELL LEFT OUTER JOIN dba.LEGAL_CONGRESS_LOC   ON WELL.UWI = LEGAL_CONGRESS_LOC.UWI and WELL.LEGAL_SURVEY_TYPE = LEGAL_CONGRESS_LOC.LOCATION_TYPE)
LEFT OUTER JOIN dba.LEGAL_TEXAS_LOC     ON WELL.UWI = LEGAL_TEXAS_LOC.UWI and WELL.LEGAL_SURVEY_TYPE = LEGAL_TEXAS_LOC.LOCATION_TYPE)
LEFT OUTER JOIN dba.LEGAL_OFFSHORE_LOC  ON WELL.UWI = LEGAL_OFFSHORE_LOC.UWI and WELL.LEGAL_SURVEY_TYPE = LEGAL_OFFSHORE_LOC.LOCATION_TYPE)
LEFT OUTER JOIN dba.LEGAL_NE_LOC        ON WELL.UWI = LEGAL_NE_LOC.UWI and WELL.LEGAL_SURVEY_TYPE = LEGAL_NE_LOC.LOCATION_TYPE )
LEFT OUTER JOIN dba.LEGAL_DLS_LOC       ON WELL.UWI = LEGAL_DLS_LOC.UWI and WELL.LEGAL_SURVEY_TYPE = LEGAL_DLS_LOC.LOCATION_TYPE ORDER BY "Well ID";
