select GX_PRODUCTION_TEST.UWI as "Well ID",
    GX_PRODUCTION_TEST.SOURCE as Source,
    GX_PRODUCTION_TEST.TEST_TYPE as "Test Type",'1' as "Run Number",
    GX_PRODUCTION_TEST.TEST_NUMBER as "Test Number",'N/A' as "Producing Zone",
    GX_PRODUCTION_TEST.TEST_DATE as "Test Date",
    GX_PRODUCTION_TEST.TOP_FORM as "Top Formation",
    GX_PRODUCTION_TEST.TOP_DEPTH as "Top Depth",
    GX_PRODUCTION_TEST.BASE_FORM as "Base Formation",
    GX_PRODUCTION_TEST.BASE_DEPTH as "Base Depth",
    GX_PRODUCTION_TEST.GX_Z_FACTOR as "Z Factor",
    GX_PRODUCTION_TEST.GX_BHP_Z as "P/Z",
    GX_PRODUCTION_TEST.GX_GAS_CUM as "Cum Gas",
    GX_PRODUCTION_TEST.TEST_DURATION as "Test Duration",
    GX_PRODUCTION_TEST.OIL_FLOW_AMT as "Oil Volume",
    GX_PRODUCTION_TEST.MAX_OIL_FLOW_RATE as "Oil Rate",
    GX_PRODUCTION_TEST.GAS_FLOW_AMT as "Gas Volume",
    GX_PRODUCTION_TEST.MAX_GAS_FLOW_RATE as "Gas Rate",
    GX_PRODUCTION_TEST.WATER_FLOW_AMT as "Water Volume",
    GX_PRODUCTION_TEST.MAX_WATER_FLOW_RATE as "Water Rate",
    GX_PRODUCTION_TEST.FLOW_PRESS as "Flow Pressure",
    GX_PRODUCTION_TEST.MAX_HYDROSTATIC_PRESS as "BH Pressure",
    GX_PRODUCTION_TEST.CHOKE_SIZE_DESC as Choke,
    GX_PRODUCTION_TEST.REPORT_TEMP as "BH Temperature",
    GX_PRODUCTION_TEST.OIL_GRAVITY as "Oil Gravity",
    DBA.GOR(GX_PRODUCTION_TEST.GAS_FLOW_AMT,GX_PRODUCTION_TEST.OIL_FLOW_AMT) as GOR,
    GX_PRODUCTION_TEST.H2S_PCT as H2S,
    GX_PRODUCTION_TEST.GX_CO2_PCT as CO2,
    GX_PRODUCTION_TEST.USER1 as "User 1",
    GX_PRODUCTION_TEST.REMARK as Remarks
    from dba.GX_PRODUCTION_TEST
    where(GX_PRODUCTION_TEST.TEST_TYPE in( 'GAS') ) 
    ORDER BY "Well ID"
    , "Source"
    , "Test Type"
    , "Test Date"
    , "Test Number"
    , "Top Formation"
;