select GX_MIOWNERSHIP.ALIASID,GX_MIOWNERSHIP.LEASEID,GX_MIOWNERSHIP.INTEREST,
    GX_MIOWNERSHIP.NETACRES,GX_TRACT.GROSSAREA
    from DBA.GX_TRACT,DBA.GX_MIOWNERSHIP
    where GX_TRACT.ALIASID = GX_MIOWNERSHIP.ALIASID 
    ORDER BY GX_MIOWNERSHIP.OWNERSHIPKEY, GX_MIOWNERSHIP.ALIASID;