select GX_MIOWNERSHIP.OWNERSHIPKEY as "Group Key",GX_MIOWNERSHIP.ALIASID as "Tract ID",
    GX_MIOWNERSHIP.LEASEID as "Lease ID",GX_MIOWNERSHIP.LESSOR as Lessor,
    GX_MIOWNERSHIP.MINERALOWNERSHIP_STATUS as "Ownership Status",
    GX_MIOWNERSHIP.INTEREST as "Lessor Interest",GX_MIOWNERSHIP.LESSEE as Lessee,
    GX_MIOWNERSHIP.REMARK as "Ownership Remark",
    GX_MIOWNERSHIP.NETACRES as "Net Area",GX_MIOWNERSHIP.SUBSTANCE as Substance,
    GX_MIOWNERSHIP.HBPWELLID as "HBP Well ID",GX_MIOWNERSHIP.FROMDEPTH as "From Depth",
    GX_MIOWNERSHIP.TODEPTH as "To Depth",GX_MIOWNERSHIP.DEPTHUNIT as "Depth Unit",
    GX_MIOWNERSHIP.DEPTHEXCEPTIONS as "Depth Exceptions",
    GX_MIOWNERSHIP.FROMQUALIFIER as "From Qualifier",
    GX_MIOWNERSHIP.TOQUALIFIER as "To Qualifier",
    GX_MIOWNERSHIP.FROMFORMATION as "From Formation",
    GX_MIOWNERSHIP.TOFORMATION as "To Formation"
    from DBA.GX_MIOWNERSHIP 
    ORDER BY GX_MIOWNERSHIP.OWNERSHIPKEY, GX_MIOWNERSHIP.ALIASID;
     