select a.UWI as "Well ID",
    a.LINER_ID as "Liner ID",
    a.TOP_DEPTH as "Top Depth",
    a.BASE_DEPTH as "Base Depth",
    a.DATA_SOURCE as "Data Source",
    a.TOP_FORMATION as "Top Formation",
    a.INSTALL_DATE as "Install Date",
    a.REMOVAL_DATE as "Removal Date",
    a.LINER_SIZE as "Liner Size",
    a.LINER_TYPE as "Liner Type",
    a.GRADE as Grade,
    a.DENSITY as Density,
    a.CONNECT_CODE as "Connect Code",
    a.HANGER_TYPE as "Hanger Type",
    a.CEMENT_TYPE as "Cement Type",
    a.CEMENT_WEIGHT as "Cement Weight",
    a.TOP_OF_CEMENT as "Top Of Cement",
    a.CEMENT_AMT as "Cement Amount",
    a.SCREEN_SIZE as "Screen Size",
    a.LEAK_OFF_TEST as "Leak Off Test",
    a.LINER_PRESSURE_TEST as "Liner Pressure Test",
    a.CEMENT_BOND_LOG_RUN as "Cement Bond Log Run",
    a.CREATE_DATE as "Create Date",
    a.CREATE_USER_ID as "Create User ID",
    a.UPDATE_USER_ID as "Update User ID",
    a.UPDATE_DATE as "Update Date",
    a.REMARK as Remark,
    a.TOP_DEPTH_OUOM as "Top Depth OUOM",
    a.BASE_DEPTH_OUOM as "Base Depth OUOM",
    a.LINER_SIZE_OUOM as "Liner Size OUOM",
    a.DENSITY_OUOM as "Density OUOM",
    a.CEMENT_WEIGHT_OUOM as "Cement Weight OUOM",
    a.TOP_OF_CEMENT_OUOM as "Top Of Cement OUOM",
    a.CEMENT_AMT_OUOM as "Cement Amount OUOM",
    a.SCREEN_SIZE_OUOM as "Screen Size OUOM",
    a.LEAK_OFF_TEST_OUOM as "Leak Off Test OUOM",
    a.LINER_PRESSURE_TEST_OUOM as "Liner Pressure Test OUOM"
    from DBA.LINER as a
    ORDER BY "Well ID"
    , "Liner ID"
    ;