select LEGAL_DLS_LOC.UWI as "Well ID",LEGAL_DLS_LOC.LOCATION_TYPE as Type,
    LEGAL_DLS_LOC.SOURCE as Source,
    LEGAL_DLS_LOC.DLS_LEGAL_SUBDIVISION as Subdivision,
    LEGAL_DLS_LOC.DLS_SECTION as Section,LEGAL_DLS_LOC.DLS_TOWNSHIP as Township,
    LEGAL_DLS_LOC.DLS_TOWNSHIP_MODIFIER as "N/S Dir",
    LEGAL_DLS_LOC.DLS_RANGE as Range,
    LEGAL_DLS_LOC.DLS_RANGE_MODIFIER as "E/W Dir",
    LEGAL_DLS_LOC.DLS_MERIDIAN_DIRECTION as "Meridian Dir",
    LEGAL_DLS_LOC.DLS_MERIDIAN as Meridian,
    LEGAL_DLS_LOC.DLS_LOC_EXCEPTION as "Exception",
    LEGAL_DLS_LOC.DLS_EVENT_SEQUENCE as "Event Seq",
    LEGAL_DLS_LOC.REMARK as "Location Description",
    LEGAL_DLS_LOC.POLYGONID
    from dba.LEGAL_DLS_LOC
    ORDER BY "Well ID"
    , "Type"
    ;