select WELL_CHECKSHOT_SURVEY.UWI as "Well ID",WELL_CHECKSHOT_SURVEY.SOURCE as Source,
    WELL_CHECKSHOT_SURVEY.SURVEY_TYPE as "Survey Type",
    WELL_CHECKSHOT_SURVEY.SURVEY_ID as "Survey ID",
    WELL_CHECKSHOT_SURVEY.SURVEY_DATE as "Date",
    WELL_CHECKSHOT_SURVEY.ENERGY_SOURCE as "Energy Source",
    WELL_CHECKSHOT_SURVEY.DATUM_ELEV as "Survey Datum",
    WELL_CHECKSHOT_SURVEY.SOURCE_DEPTH as "Source Depth",
    WELL_CHECKSHOT_SURVEY.SOURCE_OFFSET as "Source Offset",
    WELL_CHECKSHOT_SURVEY.CHECKSHOT_VELOCITY as Velocity,
    WELL_CHECKSHOT_SURVEY.GX_USER1 as "User 1",
    WELL_CHECKSHOT_SURVEY.GX_KO as Kz,
    WELL_CHECKSHOT_SURVEY.ACTIVE as Active
    from dba.WELL_CHECKSHOT_SURVEY
    ORDER BY "Well ID"
    , "Source"
    , "Survey ID"
    ;