select GX_ZATTRIBUTE.ZATTRIBUTE_NAME,GX_ZATTRIBUTE.ZATTRIBUTE_TYPE,
    GX_ZATTRIBUTE.ZATTRIBUTE_VALUE_UNIT,GX_ZATTRIBUTE.ZATTRIBUTE_DECIMALS,
    GX_ZATTRIBUTE.DOMAIN,GX_ZATTRIBUTE.GX_REMARK
    from DBA.GX_ZATTRIBUTE
    ORDER BY ZATTRIBUTE_NAME;
