SELECT WELL.UWI as "Well ID",
GX_ZONE.ZONE_NAME as "Zone Name",
WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_NAME as "Attribute Name",
WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_NUMERIC as "Numeric Attribute Value",
WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_STRING as "Character Attribute Value",
WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_DATE as "Date Attribute Value",
WELL_ZONE_INTERVAL.TVD,
WELL_ZONE_INTERVAL.TVDSS,
WELL_ZONE_INTERVAL.MD,
WELL_ZONE_INTERVAL.TOP_MD as TopMD,
WELL_ZONE_INTERVAL.BASE_MD as BaseMD,
WELL_ZONE_INTERVAL.X,
WELL_ZONE_INTERVAL.Y
from (GX_ZONE,WELL)
left outer join WELL_ZONE_INTERVAL on WELL_ZONE_INTERVAL.ZONE_NAME = GX_ZONE.ZONE_NAME and WELL_ZONE_INTERVAL.UWI = WELL.UWI
left outer join WELL_ZONE_INTRVL_VALUE on WELL_ZONE_INTRVL_VALUE.UWI = WELL.UWI and WELL_ZONE_INTRVL_VALUE.ZONE_NAME = GX_ZONE.ZONE_NAME
ORDER BY "Well ID";OUTPUT TO D:\Samples\GXDBRegression\GXDBRegression\Results\Well\WellZoneAttributeValues.sql_1.xml FORMAT XML