-- ALTER VIEW "DBA"."WellHeaderWithRemarks" AS
SELECT WELL.UWI                         AS "Well ID",
WELL.PRIMARY_SOURCE             AS Source,
WELL.OPERATOR                   AS Operator,
WELL.PROVINCE_STATE             AS State,
WELL.COUNTY                     AS County,
WELL.COUNTRY                        AS Country,
WELL.WELL_NAME                  AS "Well Name",
WELL.WELL_NUMBER                    AS "Well Number",
WELL.SURFACE_LATITUDE           AS Latitude,
WELL.SURFACE_LONGITUDE          AS Longitude,
WELL.CURRENT_STATUS             AS Status,
WELL.CURRENT_CLASS              AS Classification,
WELL.DEPTH_DATUM_ELEV           AS "Datum Elev",
WELL.GROUND_ELEV                    AS "Ground Elev",
WELL.PLUGBACK_DEPTH             AS "Plugback Depth",
WELL.FINAL_TD                   AS TD,
WELL.TD_FORM                        AS "Fm at TD",
WELL.GX_TD_FORM_ALIAS           AS "Fm Alias at TD",
WELL.SPUD_DATE                  AS "Spud Date",
WELL.COMPLETION_DATE                AS "Comp Date",
WELL.GEOLOGIC_PROVINCE          AS Area,
WELL.DISTRICT                   AS District,
WELL.ASSIGNED_FIELD             AS Field,
WELL.WELL_GOVT_ID               AS "Permit Number",
WELL.DEPTH_DATUM                    AS "Datum Type",
WELL.GX_ALTERNATE_ID                AS "Alternate ID",
WELL.GX_OLD_ID                  AS "Old ID",
WELL.GX_USER1                   AS "User 1",
WELL.GX_USER2                   AS "User 2",
WELL.LEASE_NAME                 AS "Lease Name",
WELL.PLATFORM_ID                    AS "Platform ID",
WELL.WATER_DEPTH                    AS "Water Depth",
WELL.WATER_DEPTH_DATUM          AS "Water Datum",
WELL.PARENT_RELATIONSHIP_TYPE   AS "Parent UWI Type",
WELL.GX_PERMIT_DATE             AS "Permit Date",
WELL.GX_USER_DATE               AS "User Date",
WELL.PARENT_UWI                 AS "Parent UWI",
WELL.LEGAL_SURVEY_TYPE          AS "Legal Survey Type",
WELL.GX_LOCATION_STRING         AS "Location",
WELL.GX_REMARKS                 AS "Remarks"
FROM WELL ORDER BY "Well ID";
