    SELECT 1 as ID,
    WELL.UWI as "Well ID",
    WELL.PRIMARY_SOURCE as Source,
    WELL.OPERATOR as Operator,
    WELL.PROVINCE_STATE as State,
    WELL.COUNTY as County,
    WELL.COUNTRY as Country,
    WELL.WELL_NAME as "Well Name",
    WELL.WELL_NUMBER as "Well Number",
    WELL.SURFACE_LATITUDE as Latitude,
    WELL.SURFACE_LONGITUDE as Longitude,
    WELL.CURRENT_STATUS as Status,
    WELL.CURRENT_CLASS as Classification,
    WELL.DEPTH_DATUM_ELEV as "Datum Elev",
    WELL.GROUND_ELEV as "Ground Elev",
    WELL.PLUGBACK_DEPTH as "Plugback Depth",
    WELL.FINAL_TD as TD,
    WELL.TD_FORM as "Fm at TD",
    WELL.GX_TD_FORM_ALIAS as "Fm Alias at TD",
    WELL.SPUD_DATE as "Spud Date",
    WELL.COMPLETION_DATE as "Comp Date",
    WELL.GEOLOGIC_PROVINCE as Area,
    WELL.DISTRICT as District,
    WELL.ASSIGNED_FIELD as Field,
    WELL.WELL_GOVT_ID as "Permit Number",
    WELL.DEPTH_DATUM as "Datum Type",
    WELL.GX_ALTERNATE_ID as "Alternate ID",
    WELL.GX_OLD_ID as "Old ID",
    WELL.GX_USER1 as "User 1",
    WELL.GX_USER2 as "User 2",
    WELL.LEASE_NAME as "Lease Name",
    WELL.PLATFORM_ID as "Platform ID",
    WELL.WATER_DEPTH as "Water Depth",
    WELL.WATER_DEPTH_DATUM as "Water Datum",
    WELL.PARENT_RELATIONSHIP_TYPE as "Parent UWI Type",
    WELL.GX_PERMIT_DATE as "Permit Date",
    WELL.GX_USER_DATE as "User Date",
    WELL.PARENT_UWI as "Parent UWI",
    WELL.ORIGINAL_OPERATOR as "Original Operator",
    WELL.LEGAL_SURVEY_TYPE as "Legal Survey Type",
    WELL.GX_LOCATION_STRING as Location,
    WELL.GX_DEV_WELL_BLOB as "Survey Points",
    WELL.COMMON_WELL_NAME as "Common Well Name",
    WELL.GGX_INTERNAL_STATUS as "Internal Status",
    WELL.GX_WSN as WSN,
    WELL.GX_PROPOSED_FLAG as Proposed,
    1 as "Pos Log"
    from DBA.WELL ORDER BY "Well ID";
