--ALTER VIEW "DBA"."WorkoversAndSidetracks" as
SELECT a.UWI as 'Well ID',
'HEADER' as 'Bore Type',
RIGHT(a.UWI,4) as 'Borehole',
'SCOUT CARD' as 'WORK',
NULL as "Date",
'N/A' as 'Formation',
'N/A' as 'Type',
NULL as 'Top Depth',
NULL as 'Base Depth',
'N/A' as 'Well Logs',
'N/A' as 'Oil Production',
'N/A' as 'Gas Production',
'N/A' as 'Water Production',
'N/A' as 'User1',
'N/A' as 'User2',
'N/A' as 'User3',
NULL as  'User4',
NULL as  'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL as a
UNION
select a.UWI as 'Well ID',
(case when RIGHT(a.UWI,4) = '0000' and LENGTH(a.UWI) = 14 then 'WELL' else (case when 0 < any (select count(*) from DBA.WELL as b WHERE LEFT(a.UWI,12) = LEFT(b.UWI,12) AND a.UWI <> b.UWI and CAST(SUBSTRING(a.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(a.UWI,4) as 'Borehole',
'COMPLETION' as 'Work',
DATEFORMAT(a.COMPLETION_DATE, 'Mmm dd, yyyy') as "Date",
a.COMPLETION_FORM as 'Formation',
a.COMPLETION_TYPE as 'Type',
STR(a.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(a.BASE_DEPTH, 5, 0)  as 'Base Depth',
(case when a.UWI = (select b.WELLID from DBA.GX_WELL_CURVESET as b where a.UWI = b.WELLID and (a.TOP_DEPTH BETWEEN b.TOPDEPTH AND b.BASEDEPTH or a.BASE_DEPTH BETWEEN b.TOPDEPTH and b.BASEDEPTH) group by b.WELLID) then 'Yes' else null end) as 'Well Logs',
(case when a.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_OIL_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID group by b.UWI) then  (select STR(CAST(b.CUMULATIVE_OIL_VOLUME as CHAR),8,0)  from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_OIL_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID ) else null end) as 'Oil Production',
(case when a.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_GAS_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID group by b.UWI) then   (select STR(CAST(b.CUMULATIVE_GAS_VOLUME as CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_GAS_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID ) else null end) as 'Gas Production',
(case when a.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_WATER_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID group by b.UWI) then   (select STR(CAST(b.CUMULATIVE_WATER_VOLUME as CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as b where a.UWI = b.UWI and b.CUMULATIVE_WATER_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and a.COMPLETION_FORM = b.ZONE_ID ) else null end) as 'Water Production',
'N/A' as 'User1',
'N/A' as 'User2',
'N/A' as 'User3',
NULL as  'User4',
NULL as  'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL_COMPLETION as a
UNION
select
b.UWI as 'Well ID',
(case when RIGHT(b.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as a WHERE LEFT(a.UWI,12) = LEFT(b.UWI,12) AND a.UWI <> b.UWI and CAST(SUBSTRING(b.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(b.UWI,4) as 'Borehole',
'PERF',
DATEFORMAT(b.PERFORATION_DATE, 'Mmm dd, yyyy') as "Date",
b.TOP_FORM as 'Formation',
b.PERFORATION_TYPE as 'Type',
STR(b.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(b.BASE_DEPTH, 5, 0)  as 'Base Depth',
(case when b.UWI = (select a.WELLID from DBA.GX_WELL_CURVESET as a where b.UWI = a.WELLID and (b.TOP_DEPTH BETWEEN a.TOPDEPTH AND a.BASEDEPTH or b.BASE_DEPTH BETWEEN a.TOPDEPTH and a.BASEDEPTH) group by a.WELLID) then 'Yes' else null end) as 'Well Logs',
(case when b.UWI = (select a.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_OIL_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION' and b.TOP_FORM = a.ZONE_ID group by a.UWI) then (select STR(CAST(a.CUMULATIVE_OIL_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_OIL_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and b.TOP_FORM = a.ZONE_ID ) else null end) as 'Oil Production',
(case when b.UWI = (select a.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_GAS_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and b.TOP_FORM = a.ZONE_ID group by a.UWI) then (select STR(CAST(a.CUMULATIVE_GAS_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_GAS_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and b.TOP_FORM = a.ZONE_ID )  else null end) as 'Gas Production',
(case when b.UWI = (select a.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_WATER_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and b.TOP_FORM = a.ZONE_ID group by a.UWI) then (select STR(CAST(a.CUMULATIVE_WATER_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = b.UWI and a.CUMULATIVE_WATER_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and b.TOP_FORM = a.ZONE_ID )  else null end) as 'Water Production',
STR(b.PERFORATION_COUNT, 5, 0) as 'User1',
b.PERFORATION_DIAMETER as 'User2',
b.REMARK as 'User3',
b.CURRENT_STATUS as 'User4',
NULL as 'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL_PERFORATION as b
UNION
select c.UWI as 'Well ID',
(case when RIGHT(c.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(c.UWI,12) = LEFT(b.UWI,12) AND c.UWI <> b.UWI and CAST(SUBSTRING(c.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(c.UWI,4) as 'Borehole',
'DST', null as "Date",
c.TOP_FORM as 'Formation',
c.TEST_SUBTYPE as 'Type',
STR(c.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(c.BASE_DEPTH, 5, 0)  as 'Base Depth',
(case when c.UWI = (select b.WELLID from DBA.GX_WELL_CURVESET as b where c.UWI = b.WELLID and (c.TOP_DEPTH BETWEEN b.TOPDEPTH AND b.BASEDEPTH or c.BASE_DEPTH BETWEEN b.TOPDEPTH and b.BASEDEPTH) group by b.WELLID) then 'Yes' else null end) as 'Well Logs',
(case when c.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where c.UWI = b.UWI and b.CUMULATIVE_OIL_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_OIL_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = c.UWI and a.CUMULATIVE_OIL_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = a.ZONE_ID )  else null end) as 'Oil Production',
(case when c.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where c.UWI = b.UWI and b.CUMULATIVE_GAS_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_GAS_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = c.UWI and a.CUMULATIVE_GAS_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = a.ZONE_ID )  else null end) as 'Gas Production',
(case when c.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where c.UWI = b.UWI and b.CUMULATIVE_WATER_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_WATER_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = c.UWI and a.CUMULATIVE_WATER_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and c.TOP_FORM = a.ZONE_ID )  else null end) as 'Water Production',
(case when c.UWI = (select FIRST b.UWI from DBA.WELL_TEST_RECOVERY as b WHERE c.UWI = b.UWI and c.TEST_NUMBER = b.TEST_NUMBER) then (select STR(CAST(MAX(a.RECOVERY_AMT) as CHAR),8,0) from DBA.WELL_TEST_RECOVERY as a where c.UWI = a.UWI and c.TEST_NUMBER = a.TEST_NUMBER) else null end)  as 'User1',
(case when c.UWI = (select FIRST b.UWI from DBA.WELL_TEST_RECOVERY as b WHERE c.UWI = b.UWI and c.TEST_NUMBER = b.TEST_NUMBER) then (select FIRST a.RECOVERY_TYPE from DBA.WELL_TEST_RECOVERY as a where c.UWI = a.UWI and c.TEST_NUMBER = a.TEST_NUMBER) else null end) as 'User2',
(case when c.UWI = (select FIRST b.UWI from DBA.WELL_TEST_RECOVERY as b WHERE c.UWI = b.UWI and c.TEST_NUMBER = b.TEST_NUMBER) then (select FIRST a.RECOVERY_AMT_UOM from DBA.WELL_TEST_RECOVERY as a where c.UWI = a.UWI and c.TEST_NUMBER = a.TEST_NUMBER) else null end) as 'User3',
NULL as  'User4',
NULL as  'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL_TEST as c
WHERE c.TEST_TYPE = 'DST'
UNION
select d.UWI as 'Well ID',
(case when RIGHT(d.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(d.UWI,12) = LEFT(b.UWI,12) AND d.UWI <> b.UWI and CAST(SUBSTRING(d.UWI,14,1) as NUMERIC) > 0 ) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(d.UWI,4) as 'Borehole',
'CORE',
DATEFORMAT(d.RECOVERY_DATE, 'Mmm dd, yyyy') as "Date",
d.PRIMARY_CORE_FORM as 'Formation',
d.CORE_TYPE as 'Type',
STR(d.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(d.BASE_DEPTH, 5, 0)  as 'Base Depth',
(case when d.UWI = (select b.WELLID from DBA.GX_WELL_CURVESET as b where d.UWI = b.WELLID and (d.TOP_DEPTH BETWEEN b.TOPDEPTH AND b.BASEDEPTH or d.BASE_DEPTH BETWEEN b.TOPDEPTH and b.BASEDEPTH) GROUP BY b.WELLID) then 'Yes' else null end) as 'Well Logs',
null as 'Oil Production',
null as 'Gas Production',
null as 'Water Production',
STR(d.RECOVERED_AMT, 5, 0) as 'User1',
'N/A' as 'User2',
'N/A' as 'User3',
NULL as  'User4',
NULL as  'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL_CORE as d
UNION
select e.UWI as 'Well ID',
(case when RIGHT(e.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(e.UWI,12) = LEFT(b.UWI,12) AND e.UWI <> b.UWI and CAST(SUBSTRING(e.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(e.UWI,4) as 'Borehole',
'IP',
DATEFORMAT(e.TEST_DATE, 'Mmm dd, yyyy') as "Date",
e.TOP_FORM as 'Formation',
e.TEST_SUBTYPE as 'Type',
STR(e.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(e.BASE_DEPTH, 5, 0)  as 'Base Depth',
(case when e.UWI = (select b.WELLID from DBA.GX_WELL_CURVESET as b where e.UWI = b.WELLID and (e.TOP_DEPTH BETWEEN b.TOPDEPTH AND b.BASEDEPTH or e.BASE_DEPTH BETWEEN b.TOPDEPTH and b.BASEDEPTH) group by b.WELLID) then 'Yes' else null end) as 'Well Logs',
(case when e.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where e.UWI = b.UWI and b.CUMULATIVE_OIL_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION' and e.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_OIL_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = e.UWI and a.CUMULATIVE_OIL_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and e.TOP_FORM = a.ZONE_ID )   else null end) as 'Oil Production',
(case when e.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where e.UWI = b.UWI and b.CUMULATIVE_GAS_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION' and e.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_GAS_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = e.UWI and a.CUMULATIVE_GAS_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and e.TOP_FORM = a.ZONE_ID )   else null end) as 'Gas Production',
(case when e.UWI = (select b.UWI from DBA.WELL_CUMULATIVE_PRODUCTION as b where e.UWI = b.UWI and b.CUMULATIVE_WATER_VOLUME > 0 and b.ACTIVITY_TYPE = 'PRODUCTION' and e.TOP_FORM = b.ZONE_ID group by b.UWI) then (select STR(CAST(a.CUMULATIVE_WATER_VOLUME AS CHAR),8,0) from DBA.WELL_CUMULATIVE_PRODUCTION as a where a.UWI = e.UWI and a.CUMULATIVE_WATER_VOLUME > 0 and a.ACTIVITY_TYPE = 'PRODUCTION'  and e.TOP_FORM = a.ZONE_ID )   else null end) as 'Water Production',
STR(e.OIL_FLOW_AMT, 5, 0) as 'User1',
STR(e.GAS_FLOW_AMT, 5, 0) as 'User2',
STR(e.FLOW_PRESS, 6, 0) as 'User3',
e.MAX_OIL_FLOW_RATE as  'User4',
e.MAX_GAS_FLOW_RATE as  'User5',
'N/A' as 'User6',
NULL as  'User7',
NULL as  'Date2'
from WELL_TEST as e
WHERE e.TEST_TYPE = 'IP'
UNION
select f.UWI as 'Well ID',
(case when RIGHT(f.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(f.UWI,12) = LEFT(b.UWI,12) AND f.UWI <> b.UWI and CAST(SUBSTRING(f.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(f.UWI,4) as 'Borehole',
'LINER' as 'WORK',
DATEFORMAT(f.INSTALL_DATE, 'Mmm dd, yyyy') as "Date",
f.TOP_FORMATION as 'Formation',
STR(f.LINER_ID, 5, 0) as 'Type',
STR(f.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(f.BASE_DEPTH, 5, 0) as 'Base Depth',
'N/A' as 'Well Logs',
'N/A' as 'Oil Production',
'N/A' as 'Gas Production',
'N/A' as 'Water Production',
f.TOP_DEPTH_OUOM as 'User1',
f.BASE_DEPTH_OUOM as 'User2',
f.LINER_SIZE_OUOM as 'User3',
STR(f.LINER_SIZE,5,0) as 'User4',
NULL as 'User5',
'N/A' as 'User6',
NULL as  'User7',
DATEFORMAT(f.REMOVAL_DATE, 'Mmm dd, yyyy') as "Date2"
from LINER as f
UNION
select g.UWI as 'Well ID',
(case when RIGHT(g.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(g.UWI,12) = LEFT(b.UWI,12) AND g.UWI <> b.UWI and CAST(SUBSTRING(g.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(g.UWI,4) as 'Borehole',
'WELLCASING' as 'WORK',
DATEFORMAT(g.INSTALL_DATE, 'Mmm dd, yyyy') as "Date",
g.TOP_FORMATION as 'Formation',
STR(g.CASING_ID, 5, 0) as 'Type',
STR(g.TOP_DEPTH, 5, 0) as 'Top Depth',
STR(g.BASE_DEPTH, 5, 0) as 'Base Depth',
'N/A' as 'Well Logs',
'N/A' as 'Oil Production',
'N/A' as 'Gas Production',
'N/A' as 'Water Production',
g.CASING_SIZE_OUOM as 'User1',
g.INSIDE_DIAMETER_OUOM as 'User2',
g.TOP_DEPTH_OUOM as 'User3',
STR(g.CASING_SIZE, 5, 0) as 'User4',
STR(g.INSIDE_DIAMETER, 5, 0) as 'User5',
g.BASE_DEPTH_OUOM as 'User6',
g.NOMINAL_WEIGHT as  'User7',
DATEFORMAT(g.UPDATE_DATE, 'Mmm dd, yyyy') as "Date2"
from CASING as g
UNION
select h.UWI as 'Well ID',
(case when RIGHT(h.UWI,4) = '0000' then 'WELL' else (case when 0 < any(select count(*) from DBA.WELL as b WHERE LEFT(h.UWI,12) = LEFT(b.UWI,12) AND h.UWI <> b.UWI and CAST(SUBSTRING(h.UWI,14,1) as NUMERIC) > 0) then 'WO' else 'SIDETRACK' end) end) as 'Bore Type',
RIGHT(h.UWI,4) as 'Borehole',
'TUBING' as 'WORK',
DATEFORMAT(h.TUBING_INSTALL_DTE, 'Mmm dd, yyyy') as "Date",
h.TOP_FORMATION as 'Formation',
STR(h.TUBING_STRING_NO, 5, 0) as 'Type',
STR(h.TUBING_SET_DEPTH, 5, 0) as 'Top Depth',
'N/A' as 'Base Depth',
'N/A' as 'Well Logs',
'N/A' as 'Oil Production',
'N/A' as 'Gas Production',
'N/A' as 'Water Production',
h.TUBING_SET_DEPTH_OUOM as 'User1',
h.TUBING_SIZE_OUOM as 'User2',
'N/A' as 'User3',
STR(h.TUBING_SIZE, 5, 0) as 'User4',
NULL as 'User5',
'N/A' as 'User6',
NULL as  'User7',
DATEFORMAT(h.TUBING_REMOVE_DTE, 'Mmm dd, yyyy') as "Date2"
from TUBING as h
ORDER BY "Well ID";
