select GX_ZONE.ZONE_NAME,GX_ZONE.GX_TOP_FORM_NAME,GX_ZONE.GX_BASE_FORM_NAME,
    GX_ZONE.GX_TOP_OFFSET,GX_ZONE.GX_BASE_OFFSET,GX_ZONE.GX_TOP_MODIFIER,
    GX_ZONE.GX_BASE_MODIFIER,GX_ZONE.GX_TOPMIDBASE,GX_ZONE.DOMAIN,GX_ZONE.GX_REMARK
    from DBA.GX_ZONE
    ORDER BY GX_ZONE.ZONE_NAME;
