 select a.UWI as "Well ID",
    a.CASING_ID as "Casing ID",
    a.DATA_SOURCE as "Data Source",
    a.CASING_SIZE as "Casing Size",
    a.INSIDE_DIAMETER as "Inside Diameter",
    a.TOP_DEPTH as "Top Depth",
    a.BASE_DEPTH as "Base Depth",
    a.TOP_FORMATION as "Top Formation",
    a.BASE_FORMATION as "Base Formation",
    a.CASING_TYPE as "Casing Type",
    a.NOMINAL_WEIGHT as "Nominal Weight",
    a.GRADE as Grade,
    a.THREAD_TYPE as "Thread Type",
    a.MANUFACTURER as Manufacturer,
    a.MULTISTAGE_DEPTH as "Multistage Depth",
    a.CEMENT_TYPE as "Cement Type",
    a.CEMENT_AMT as "Cement Amount",
    a.CEMENT_WEIGHT as "Cement Weight",
    a.HOLE_SIZE as "Hole Size",
    a.TOP_OF_CEMENT as "Top Of Cement",
    a.SLURRY_VOL as "Slurry Volume",
    a.CONNECT_CODE as "Connect Code",
    a.INSTALL_DATE as "Install Date",
    a.LEAK_OFF_TEST as "Leak Off Test",
    a.CASING_PRESSURE_TEST as "Casing Pressure Test",
    a.CREATE_DATE as "Create Date",
    a.CREATE_USER_ID as "Create User ID",
    a.UPDATE_USER_ID as "Update User ID",
    a.UPDATE_DATE as "Update Date",
    a.REMARK as Remark,
    a.CASING_SIZE_OUOM as "Casing Size OUOM",
    a.INSIDE_DIAMETER_OUOM as "Inside Diameter OUOM",
    a.TOP_DEPTH_OUOM as "Top Depth OUOM",
    a.BASE_DEPTH_OUOM as "Base Depth OUOM",
    a.NOMINAL_WEIGHT_OUOM as "Nominal Weight OUOM",
    a.MULTISTAGE_DEPTH_OUOM as "Multistage Depth OUOM",
    a.CEMENT_AMT_OUOM as "Cement Amount OUOM",
    a.CEMENT_WEIGHT_OUOM as "Cement Weight OUOM",
    a.HOLE_SIZE_OUOM as "Hole Size OUOM",
    a.TOP_OF_CEMENT_OUOM as "Top Of Cement OUOM",
    a.SLURRY_VOL_OUOM as "Slurry Volume OUOM",
    a.LEAK_OFF_TEST_OUOM as "Leak Off Test OUOM",
    a.CASING_PRESSURE_TEST_OUOM as "Casing Pressure Test OUOM"
    from DBA.CASING as a
    ORDER BY "Well ID"
    , "Casing ID"
    ;