select GX_BUSASSOC.NAMEID as Name,GX_BUSASSOC.ALIAS as Alias,
GX_BUSASSOC.SSN as "SSN/Tax ID",GX_BUSASSOC.REMARK as Remarks,
GX_BUSASSOC.ATTENTION as Attention,GX_BUSASSOC.ADDRESS1 as "Address 1",
GX_BUSASSOC.ADDRESS2 as "Address 2",GX_BUSASSOC.CITY as City,
GX_BUSASSOC.STATEPROVINCE as "State/Province",GX_BUSASSOC.COUNTRY as Country,
GX_BUSASSOC.ZIP as Zip,GX_BUSASSOC.PHONE as Phone,GX_BUSASSOC.FAX as Fax,
GX_BUSASSOC.EMAIL as Email
from DBA.GX_BUSASSOC
ORDER BY Name;
