select WELL_DIR_PROPOSED_SRVY.UWI as "Well ID",WELL_DIR_PROPOSED_SRVY.SOURCE as Source,
    WELL_DIR_PROPOSED_SRVY.SURVEY_ID as "Survey ID",
    WELL_DIR_PROPOSED_SRVY.SURVEY_DATE as "Survey Date",
    WELL_DIR_PROPOSED_SRVY.COMPUTE_METHOD as "Calculation Method",
    WELL_DIR_PROPOSED_SRVY.MAGNETIC_DECLINATION as "Magnetic Declination",
    WELL_DIR_PROPOSED_SRVY.GX_KOP_MD as "KOP MD",
    WELL_DIR_PROPOSED_SRVY.GX_BASE_TVD as "BH TVD",
    WELL_DIR_PROPOSED_SRVY.GX_LP_TVD as "LP TVD",
    WELL_DIR_PROPOSED_SRVY.GX_BASE_E_W_OFFSET as "BH E/W Offset",
    WELL_DIR_PROPOSED_SRVY.GX_BASE_N_S_OFFSET as "BH N/S Offset",
    WELL_DIR_PROPOSED_SRVY.GX_LP_E_W_OFFSET as "LP E/W Offset",
    WELL_DIR_PROPOSED_SRVY.GX_LP_N_S_OFFSET as "LP N/S Offset",
    WELL_DIR_PROPOSED_SRVY.GX_BASE_LONGITUDE as "BH Longitude",
    WELL_DIR_PROPOSED_SRVY.GX_BASE_LATITUDE as "BH Latitude",
    WELL_DIR_PROPOSED_SRVY.GX_FOOTAGE as Footage,
    WELL_DIR_PROPOSED_SRVY.GX_BASE_LOCATION_STRING as "S/T/R",
    DBA.GET_CLOSURE(WELL_DIR_PROPOSED_SRVY.GX_BASE_N_S_OFFSET,WELL_DIR_PROPOSED_SRVY.GX_BASE_E_W_OFFSET) as Closure,
    WELL_DIR_PROPOSED_SRVY.CALCULATION_REQUIRED as "Calculation Required",
    WELL_DIR_PROPOSED_SRVY.NORTH_REFERENCE as "North Reference",
    WELL_DIR_PROPOSED_SRVY.GX_ACTIVE as Active,
    WELL_DIR_PROPOSED_SRVY.GX_SCENARIO_NAME as Name
    from dba.WELL_DIR_PROPOSED_SRVY 
    ORDER BY "Well ID", "Survey ID";

