select GX_PDEN_VOL_SUM_BY_MONTH.UWI as "Well ID",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_TYPE as "PDEN Type",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_SOURCE as Source,
    GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_METHOD as "Summary Type",
    GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID as Zone,
    DBA.Get_Prod_Zone_Alias(GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID) as "Zone Alias",
    GX_PDEN_VOL_SUM_BY_MONTH.PDEN_DATE as "Date",
    GX_PDEN_VOL_SUM_BY_MONTH.ACTIVITY_TYPE as "Activity Type",
    GX_PDEN_VOL_SUM_BY_MONTH.PRIMARY_PRODUCT as Product,
    GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Oil,
    GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Gas,
    GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Water,
    GX_PDEN_VOL_SUM_BY_MONTH.CO2_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as CO2,
    GX_PDEN_VOL_SUM_BY_MONTH.INJECTION_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Injection,
    GX_PDEN_VOL_SUM_BY_MONTH.NGL_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as NGL,
    GX_PDEN_VOL_SUM_BY_MONTH.NITROGEN_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Nitrogen,
    GX_PDEN_VOL_SUM_BY_MONTH.SULPHUR_VOLUME*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as Sulphur,
    DBA.OILRATE(GX_PDEN_VOL_SUM_BY_MONTH.PROD_TIME,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME) as "Oil Rate",
    DBA.GASRATE(GX_PDEN_VOL_SUM_BY_MONTH.PROD_TIME,GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME) as "Gas Rate",
    DBA.WATERRATE(GX_PDEN_VOL_SUM_BY_MONTH.PROD_TIME,GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME) as "Water Rate",
    DBA.TOTFLUIDS(GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME)*GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION/100 as "Total Fluids",
    DBA.GOR(GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME) as GOR,
    DBA.OCUT(GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME) as "Oil Cut",
    DBA.WOR(GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME) as WOR,
    DBA.GAS_YIELD(GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.OIL_VOLUME) as Yield,
    DBA.WGR(GX_PDEN_VOL_SUM_BY_MONTH.WATER_VOLUME,GX_PDEN_VOL_SUM_BY_MONTH.GAS_VOLUME) as WGR,
    GX_PDEN_VOL_SUM_BY_MONTH.PROD_TIME as "Days On",
    GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_YEAR as Year,
    GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_MONTH as Month,
    GX_PDEN_VOL_SUM_BY_MONTH.GX_PERCENT_ALLOCATION as "Percent Allocation",
    GX_PDEN_VOL_SUM_BY_MONTH.CUM_FLAG as "Cum Flag"
    from DBA.GX_PDEN_VOL_SUM_BY_MONTH left outer join DBA.FM_ALIAS_GROUP_MEMBER as b on(GX_PDEN_VOL_SUM_BY_MONTH.ZONE_ID = b.MEMBER_FM_ID)
    where GX_PDEN_VOL_SUM_BY_MONTH.PDEN_TYPE = 'WELL'
    and GX_PDEN_VOL_SUM_BY_MONTH.VOLUME_METHOD in( 'Monthly') 
    ORDER BY "Well ID"
	, "PDEN TYPE"
	, "Source"
	, "Summary Type"
	, "Zone"
	, "Date"
	, "Activity Type"
	;