select FORMATION.COLUMN_NAME as "Column Name",FORMATION.FORM_ID as ID,FORMATION.SOURCE as Source,
    DBA.GET_ALIAS_LIST(FORMATION.FORM_ID) as Alias,FORMATION.FORM_AGE as Age,
    FORMATION.FORM_NAME as Name,FORMATION.GROUP_CODE as "Group ID",
    FORMATION.GX_DOMINANT_LITHOLOGY as Lithology,
    FORMATION.GX_FORMATION_DESCRIPTION as Description,
    FORMATION.GX_VENDOR_NO as "Age Code",FORMATION.GX_INTERNAL as "Internal ID",
    FORMATION.GX_FORMATION_TYPE as Type,
    FORMATION.FORM_ABRV as Abbreviation,FORMATION.GX_WEIGHT as "Line Weight",
    FORMATION.GX_COLOR as "Line Color",FORMATION.GX_STYLE as "Line Style",
    FORMATION.GX_STRAT_SEQUENCE as "Sequence No",FORMATION.GX_ACTIVE as Active
    from dba.FORMATION
    where not FORMATION.FORM_ID = 
    any(select FM_ALIAS_GROUP_MEMBER.MEMBER_FM_ID from DBA.FM_ALIAS_GROUP_MEMBER where FM_ALIAS_GROUP_MEMBER.FORM_ID <> FM_ALIAS_GROUP_MEMBER.MEMBER_FM_ID and FM_ALIAS_GROUP_MEMBER.ALIAS_CODE <> 2) 
    ORDER BY ID, "Column Name";
