select GX_DLS_GRID.POLYGONID as "POLYGON ID",GX_DLS_GRID.SECTION as SECTION,
    GX_DLS_GRID.TOWNSHIP as TOWNSHIP,
    GX_DLS_GRID.TOWNSHIP_MODIFIER as "TOWNSHIP MODIFIER",
    GX_DLS_GRID.RANGE as RANGE,GX_DLS_GRID.RANGE_MODIFIER as "RANGE MODIFIER",
    GX_DLS_GRID.MERIDIAN_DIRECTION as "MERIDIAN DIRECTION",
    GX_DLS_GRID.MERIDIAN as MERIDIAN,GX_DLS_GRID.LSD_PARCEL as "LSD PARCEL",
    GX_DLS_GRID.MINX as "MINIMUM X",GX_DLS_GRID.MINY as "MINIMUM Y",
    GX_DLS_GRID.MAXX as "MAXIMUM X",GX_DLS_GRID.MAXY as "MAXIMUM Y",
    GX_DLS_GRID.MAJORCODE as "MAJOR CODE",GX_DLS_GRID.MINORCODE as "MINOR CODE",
    GX_DLS_GRID.ISPARTIAL as "IS PARTIAL",GX_DLS_GRID.POLYGONBLOB as "POLYGON BLOB"
    from DBA.GX_DLS_GRID
    ORDER BY "POLYGON ID";
