select LEGAL_NTS_LOC.LOCATION_ID as "Well ID",LEGAL_NTS_LOC.LOCATION_TYPE as Type,
    LEGAL_NTS_LOC.SOURCE as Source,LEGAL_NTS_LOC.SIXTEENTH as Sixteenth,
    LEGAL_NTS_LOC.QUARTER_UNIT as Quarter,
    LEGAL_NTS_LOC.PRIMARY_QUADRANGLE as "Primary",LEGAL_NTS_LOC.UNIT as Unit,
    LEGAL_NTS_LOC.BLOCK as Block,LEGAL_NTS_LOC.LETTER_QUADRANGLE as Letter,
    LEGAL_NTS_LOC.REMARK as "Location Description",LEGAL_NTS_LOC.POLYGONID
    from DBA.LEGAL_NTS_LOC
    ORDER BY "Well ID"
    , "Type"
    ;