select GX_CONGRESS_GRID.POLYGONID as "POLYGON ID",GX_CONGRESS_GRID.RANGE as RANGE,
    GX_CONGRESS_GRID.RANGE_DIR as "RANGE DIRECTION",
    GX_CONGRESS_GRID.SECTION as SECTION,GX_CONGRESS_GRID.TOWNSHIP as TOWNSHIP,
    GX_CONGRESS_GRID.TWP_NAME as "TOWNSHIP NAME",
    GX_CONGRESS_GRID.TOWNSHIP_DIR as "TOWNSHIP DIRECTION",
    GX_CONGRESS_GRID.PRINCIPAL_MERIDIAN as "PRINCIPAL MERIDIAN",
    GX_CONGRESS_GRID.PROVINCE_STATE as STATE,GX_CONGRESS_GRID.COUNTY as COUNTY,
    GX_CONGRESS_GRID.COUNTRY as COUNTRY,GX_CONGRESS_GRID.REMARK as REMARK,
    GX_CONGRESS_GRID.MINX as "MINIMUM X",GX_CONGRESS_GRID.MINY as "MINIMUM Y",
    GX_CONGRESS_GRID.MAXX as "MAXIMUM X",GX_CONGRESS_GRID.MAXY as "MAXIMUM Y",
    GX_CONGRESS_GRID.MAJORCODE as "MAJOR CODE",
    GX_CONGRESS_GRID.MINORCODE as "MINOR CODE",
    GX_CONGRESS_GRID.ISPARTIAL as "IS PARTIAL",
    GX_CONGRESS_GRID.POLYGONBLOB as "POLYGON BLOB"
    from DBA.GX_CONGRESS_GRID 
    ORDER BY "POLYGON ID";