select WELL_TEST_FLOW.UWI as "Well ID",
    WELL_TEST_FLOW.SOURCE as Source,
    WELL_TEST_FLOW.TEST_TYPE as "Test Type",
    WELL_TEST_FLOW.TEST_NUMBER as "DST ID",
    WELL_TEST_FLOW.PERIOD_TYPE as "Period Type",
    WELL_TEST_FLOW.FLUID_TYPE as Fluid,
    WELL_TEST_FLOW.RUN_NUMBER as "Run Number",
    WELL_TEST_FLOW.MAX_FLUID_RATE as Amount,
    WELL_TEST_FLOW.MAX_FLUID_RATE_UOM as Unit,
    WELL_TEST_FLOW.TTS_ELASPED_TIME as Duration,
    WELL_TEST_FLOW.MAX_SURFACE_PRESS as Pressure,
    WELL_TEST_FLOW.REMARK as Remarks,
    WELL_TEST_FORMATION.FORM_ID as Formation,
    WELL_TEST_FORMATION.AGE_CODE as Age,
    WELL_TEST.TOP_DEPTH as Depth
    from dba.WELL_TEST,dba.WELL_TEST_FLOW
    left outer join dba.WELL_TEST_FORMATION on(WELL_TEST_FLOW.UWI = WELL_TEST_FORMATION.UWI and WELL_TEST_FLOW.TEST_NUMBER = WELL_TEST_FORMATION.TEST_NUMBER)
    where WELL_TEST.UWI = WELL_TEST_FLOW.UWI and WELL_TEST.TEST_NUMBER = WELL_TEST_FLOW.TEST_NUMBER and WELL_TEST_FLOW.TEST_TYPE = 'DST' and WELL_TEST.TEST_TYPE = 'DST'
    ORDER BY  "Well ID"
    , Source
    , "Test Type"
    , "DST ID"
    , Fluid
    ;