select WELL_ZONE_INTRVL_VALUE.UWI,WELL_ZONE_INTRVL_VALUE.ZONE_NAME,
    WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_NAME,
    WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_NUMERIC,
    WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_STRING,
    WELL_ZONE_INTRVL_VALUE.ZATTRIBUTE_VALUE_DATE,
    WELL_ZONE_INTRVL_VALUE.GX_REMARK
    from DBA.WELL_ZONE_INTRVL_VALUE
    ORDER BY UWI, ZONE_NAME, ZATTRIBUTE_NAME;

