select LEGAL_TEXAS_LOC.UWI as "Well ID",LEGAL_TEXAS_LOC.LOCATION_TYPE as Type,
    LEGAL_TEXAS_LOC.SOURCE as Source,LEGAL_TEXAS_LOC.TEXAS_SURVEY as Survey,
    LEGAL_TEXAS_LOC.ABSTRACT_NUMBER as Abstract,
    LEGAL_TEXAS_LOC.TEXAS_LOT as Lot,LEGAL_TEXAS_LOC.TEXAS_BLOCK as Block,
    LEGAL_TEXAS_LOC.TEXAS_TOWNSHIP as Township,
    LEGAL_TEXAS_LOC.NS_DIRECTION as "N/S Dir",
    LEGAL_TEXAS_LOC.TEXAS_RANGE as Range,
    LEGAL_TEXAS_LOC.EW_DIRECTION as "E/W Dir",
    LEGAL_TEXAS_LOC.TEXAS_SECTION as Section,
    LEGAL_TEXAS_LOC.SECTION_FRACTION as "Part Number",
    LEGAL_TEXAS_LOC.PROVINCE_STATE as State,
    LEGAL_TEXAS_LOC.GX_RAILROAD_DISTRICT as "Railroad District",
    LEGAL_TEXAS_LOC.COUNTY as County,
    LEGAL_TEXAS_LOC.REMARK as "Location Description"
    from dba.LEGAL_TEXAS_LOC 
    ORDER BY "Well ID"
    , "Type"
    ;