    select GX_LEASE.LEASEID,GX_LEASE.COUNTERID,GX_LEASE.NAME,GX_LEASE.LEASE_TYPE,
    GX_LEASE.CATEGORY,GX_LEASE.ACTIVITY,GX_LEASE.ACQUISITIONDATE,
    GX_LEASE.LEASE_DATE,GX_LEASE.EFFECTIVEDATE,GX_LEASE.TERM,GX_LEASE.TERMUNIT,
    GX_LEASE.EXPIRATIONDATE,GX_LEASE.OPERATOR,GX_LEASE.PROSPECTFIELD,
    GX_LEASE.COUNTYPARISH,GX_LEASE.STATEPROVINCE,GX_LEASE.GROSSAREA,
    GX_LEASE.AREAUNIT,GX_LEASE.BOOK,GX_LEASE.PAGE,GX_LEASE.MICRO,GX_LEASE.REMARK,
    GX_LEASE.TOTALBONUS,GX_LEASE.RENT_SI_AMT,GX_LEASE.RENT_PAID_BY,
    GX_LEASE.DISPOSITION,GX_LEASE.RENTALDATE,GX_LEASE.RENTALTERM,GX_LEASE.ROYALTY,
    GX_LEASE.OVERRIDE,GX_LEASE.BONUSPERACRE,GX_LEASE.RENTALTERMUNIT,
    GX_LEASE.OURLEASEFLAG,GX_LEASE.USER1,GX_LEASE.USER2,
    GX_MIOWNERSHIP.OWNERSHIPKEY,GX_MIOWNERSHIP.ALIASID,GX_MIOWNERSHIP.LESSOR,
    GX_MIOWNERSHIP.MINERALOWNERSHIP_STATUS,GX_MIOWNERSHIP.INTEREST,
    GX_MIOWNERSHIP.LESSEE,GX_MIOWNERSHIP.REMARK as REMARK2,GX_MIOWNERSHIP.NETACRES,
    GX_MIOWNERSHIP.HBPWELLID,GX_MIOWNERSHIP.SUBSTANCE,GX_MIOWNERSHIP.FROMDEPTH,
    GX_MIOWNERSHIP.TODEPTH,GX_MIOWNERSHIP.DEPTHUNIT,GX_MIOWNERSHIP.DEPTHEXCEPTIONS,
    GX_MIOWNERSHIP.FROMQUALIFIER,GX_MIOWNERSHIP.FROMFORMATION,
    GX_MIOWNERSHIP.TOQUALIFIER,GX_MIOWNERSHIP.TOFORMATION
    from DBA.GX_LEASE,DBA.GX_MIOWNERSHIP where(
    GX_LEASE.LEASEID = GX_MIOWNERSHIP.LEASEID or
    GX_MIOWNERSHIP.LEASEID is null) 
    ORDER BY GX_LEASE.LEASEID, GX_MIOWNERSHIP.OWNERSHIPKEY, GX_MIOWNERSHIP.ALIASID;
    