select WELL_DIR_SRVY_STATION.UWI as WellID,
    WELL_DIR_SRVY_STATION.SOURCE as Source,
    WELL_DIR_SRVY_STATION.SURVEY_ID as SurveyID,
    WELL_DIR_SRVY_STATION.STATION_MD as MD,
    WELL_DIR_SRVY_STATION.STATION_ID as SurveyPointNumber,
    WELL_DIR_SRVY_STATION.STATION_TVD as TVD,
    WELL_DIR_SRVY_STATION.INCLINATION as Inclination,
    WELL_DIR_SRVY_STATION.AZIMUTH as Azimuth,
    WELL_DIR_SRVY_STATION.Y_OFFSET as NSOffset,
    WELL_DIR_SRVY_STATION.X_OFFSET as EWOffset,
    WELL_DIR_SRVY_STATION.GX_STATION_LATITUDE as LatY,
    WELL_DIR_SRVY_STATION.GX_STATION_LONGITUDE as LongX,
    DBA.SRVYCLOSURE(WELL_DIR_SRVY_STATION.X_OFFSET,WELL_DIR_SRVY_STATION.Y_OFFSET) as Closure
    from DBA.WELL_DIR_SRVY_STATION 
    ORDER BY WellID, MD;
