select WELL_PERFORATION.UWI as "Well ID",
    WELL_PERFORATION.SOURCE as Source,
    WELL_PERFORATION.PERFORATION_OBS_NO as "Observation Number",
    WELL_PERFORATION.COMPLETION_OBS_NO as "Comp. Observation Number",
    WELL_PERFORATION.COMPLETION_SOURCE as "Comp. Source",
    WELL_PERFORATION.TOP_DEPTH as "Top",
    WELL_PERFORATION.BASE_DEPTH as Base,
    WELL_PERFORATION.TOP_FORM as "Top Fm",
    WELL_PERFORATION.BASE_FORM as "Base Fm",
    WELL_PERFORATION.PERFORATION_DATE as "Date",
    WELL_PERFORATION.PERFORATION_TYPE as Type,
    WELL_PERFORATION.PERFORATION_DENSITY as Density,
    WELL_PERFORATION.PERFORATION_DIAMETER as Diameter,
    WELL_PERFORATION.PERFORATION_PHASE as Phase,
    WELL_PERFORATION.PERFORATION_ANGLE as Angle,
    WELL_PERFORATION.PERFORATION_COUNT as Count,
    WELL_PERFORATION.CURRENT_STATUS as "Current Status",
    WELL_PERFORATION.REMARK as Remarks,
    WELL_PERFORATION.CLUSTER as "Perf Cluster",
    WELL_PERFORATION.STAGE as Stage
    from dba.WELL_PERFORATION
    ORDER BY "Well ID"
    , Source
    , "OBservation Number"
    , "Comp. Observation Number"
    , "Comp. Source"
    , PERFORATION_OBS_NO
    ;
