select WELL_CHECKSHOT_SURVEY.SURVEY_TYPE as "Survey Type",

    WELL_CHECKSHOT_SURVEY.SURVEY_ID as "ID",
    WELL_CHECKSHOT_SURVEY.UWI as "Well ID",
    WELL_CHECKSHOT_SURVEY.Source as "Source",
    WELL_CHECKSHOT_SURVEY.SURVEY_DATE as "Survey Date",
    WELL_CHECKSHOT_SURVEY.SURVEY_RUN_NO as "Run Number",
    WELL_CHECKSHOT_SURVEY.DATUM_ELEV as "Datum Elev",
    WELL_CHECKSHOT_SURVEY.CHECKSHOT_VELOCITY as "Datum Velocity",
    WELL_VELOCITY.SEISMIC_TIME_DATUM as "Seismic Datum Elev",
    WELL_VELOCITY.VELOCITY_VALUE as "Seismic Datum Velocity",'NO FIELD ERROR' as K,
    WELL_CHECKSHOT_SURVEY.ENERGY_SOURCE as "Source Type",
    WELL_CHECKSHOT_SURVEY.SOURCE_OFFSET as "Source Offset",
    WELL_CHECKSHOT_SURVEY.SOURCE_AZIMUTH as "Source Azimuth",
    WELL_CHECKSHOT_SURVEY.SOURCE_DEPTH as "Source Depth",
    WELL_CHECKSHOT_DETAIL.SHOT_NUMBER as "Shot Number",
    WELL_CHECKSHOT_DETAIL.GEOPHONE_MD as Depth,
    WELL_CHECKSHOT_DETAIL.OBSERVED_TIME as "1-Way Time",'NO FIELD ERROR' as "Seismic Data Time",
    WELL_VELOCITY.VELOCITY_VALUE as "Average Velocity",
    WELL_VELOCITY.VELOCITY_VALUE as "Interval Velocity"
    from dba.WELL_CHECKSHOT_SURVEY,dba.WELL_VELOCITY,dba.WELL_CHECKSHOT_DETAIL 
    ORDER BY "Well ID"
    , "ID"
    , "Shot Number"
    , Source
    ;