select LEGAL_OHIO_LOC.LOCATION_ID as "Well ID",LEGAL_OHIO_LOC.LOCATION_TYPE as Type,
    LEGAL_OHIO_LOC.SOURCE as Source,LEGAL_OHIO_LOC.MAP_QUAD_MIN as "Quad Min",
    LEGAL_OHIO_LOC.MAP_QUAD_NAME as "Quad Name",
    LEGAL_OHIO_LOC.NS_FOOTAGE as "N/S Footage",
    LEGAL_OHIO_LOC.NS_START_LINE as "N/S Start Line",
    LEGAL_OHIO_LOC.EW_FOOTAGE as "E/W Footage",
    LEGAL_OHIO_LOC.EW_START_LINE as "E/W Start Line",
    LEGAL_OHIO_LOC.FOOTAGE_ORIGIN as Origin,
    LEGAL_OHIO_LOC.SPOT_CODE as "Spot Code",
    LEGAL_OHIO_LOC.PRINCIPAL_MERIDIAN as Meridian,
    LEGAL_OHIO_LOC.OHIO_TOWNSHIP_NAME as "TWP Name",
    LEGAL_OHIO_LOC.OHIO_TWP_SECT_CODE as Section,
    LEGAL_OHIO_LOC.OHIO_TWP_LOT_CODE as Lot,
    LEGAL_OHIO_LOC.PROVINCE_STATE as State,LEGAL_OHIO_LOC.COUNTY as County,
    LEGAL_OHIO_LOC.COUNTRY as Country,
    LEGAL_OHIO_LOC.REMARK as "Location Description",
    LEGAL_OHIO_LOC.POLYGONID
    from dba.LEGAL_OHIO_LOC
    ORDER BY "Well ID"
    , "Type"
    ; 