select GX_NORTH_SEA_GRID.POLYGONID as "POLYGON ID",
    GX_NORTH_SEA_GRID.QUADRANT as QUADRANT,
    GX_NORTH_SEA_GRID.QUADRANT_PREFIX as "QUADRANT PREFIX",
    GX_NORTH_SEA_GRID.BLOCK_NO as "BLOCK NUMBER",
    GX_NORTH_SEA_GRID.BLOCK_SUFFIX as "BLOCK SUFFIX",
    GX_NORTH_SEA_GRID.MERIDIAN as MERIDIAN,GX_NORTH_SEA_GRID.MINX as "MINIMUM X",
    GX_NORTH_SEA_GRID.MAXX as "MAXIMUM X",GX_NORTH_SEA_GRID.MINY as "MINIMUM Y",
    GX_NORTH_SEA_GRID.MAXY as "MAXIMUM Y",
    GX_NORTH_SEA_GRID.MAJORCODE as "MAJOR CODE",
    GX_NORTH_SEA_GRID.MINORCODE as "MINOR CODE",
    GX_NORTH_SEA_GRID.ISPARTIAL as "IS PARTIAL",
    GX_NORTH_SEA_GRID.POLYGONBLOB as "POLYGON BLOB"
    from DBA.GX_NORTH_SEA_GRID
    ORDER BY "POLYGON ID";