select GX_MINERALZONE.GROUPKEY as "Group Key",GX_MINERALZONE.ALIASID as "Tract ID",
    GX_MINERALZONE.LEASEID as "Lease ID",
    GX_MINERALZONE.MINERALZONE_STATUS as "Producing Status",
    GX_MINERALZONE.SUBSTANCE as Substance,
    GX_MINERALZONE.TOFORMATION as "To Formation",
    GX_MINERALZONE.TOQUALIFIER as "To Qualifier",
    GX_MINERALZONE.DEPTH_EXCEPTIONS as "Depth Exceptions",
    GX_MINERALZONE.TODEPTH as "To Depth",GX_MINERALZONE.DEPTHUNIT as "Depth Unit",
    GX_MINERALZONE.FROMDEPTH as "From Depth",
    GX_MINERALZONE.FROMFORMATION as "From Formation",
    GX_MINERALZONE.FROMQUALIFIER as "From Qualifier"
    from DBA.GX_MINERALZONE 
    ORDER BY GROUPKEY;
    