select LEGAL_NORTH_SEA_LOC.LOCATION_ID as "Well ID",
    LEGAL_NORTH_SEA_LOC.LOCATION_TYPE as Type,
    LEGAL_NORTH_SEA_LOC.SOURCE as Source,
    LEGAL_NORTH_SEA_LOC.QUADRANT as Quadrant,
    LEGAL_NORTH_SEA_LOC.QUADRANT_PREFIX as "Quadrant Prefix",
    LEGAL_NORTH_SEA_LOC.BLOCK_NO as Block,
    LEGAL_NORTH_SEA_LOC.BLOCK_SUFFIX as "Block Suffix",
    LEGAL_NORTH_SEA_LOC.WELL_SEQUENCE_NO as "Well Seq No",
    LEGAL_NORTH_SEA_LOC.WELL_NO_SUFFIX as "Well Suffix",
    LEGAL_NORTH_SEA_LOC.WELL_NO_PREFIX as "Well Prefix",
    LEGAL_NORTH_SEA_LOC.LAND_WELL_IND as "Land Ind",
    LEGAL_NORTH_SEA_LOC.PRINCIPAL_MERIDIAN as Meridian,
    LEGAL_NORTH_SEA_LOC.REMARK as "Location Description",
    LEGAL_NORTH_SEA_LOC.POLYGONID
    from dba.LEGAL_NORTH_SEA_LOC
    ORDER BY "Well ID"
    , "Type"
    ;